### ISSUE TITLE
Подписание файлов большого размера

### ISSUE THREAD

**Issue by kochnev93** [bad4iz/crypto-pro-cadesplugin#1]
Добрый день, с использованием данной библиотеки без проблем получается подписать небольшие файлы (использую метод signBase64). Попробовал подписать файл размером 180мб получил ошибку "Lost connection to extension". Можно ли в рамках данной библиотеки подписывать файл по частям или нужно реализовывать кастомное решение? https://cpdn.cryptopro.ru/?url=/content/cades/plugin-samples-fileapi_stream.html 

На тестовой странице получаю такую же ошибку, https://bad4iz.github.io/file-signature-in-react/?path=/story/%D0%BF%D0%BE%D0%B4%D0%BF%D0%B8%D1%81%D1%8C-%D1%84%D0%B0%D0%B9%D0%BB%D0%B0--file-signature-cripto-pro

Спасибо.

**Comment by bad4iz** [comment]
К сожалению существует ограничение по размеру подписания файла. Имено подписания а не чтения файла.

Писал в поддержку самим криптопро ответ был что в данном случае нужно использовать десктопную версию для подписания большого файла. Размер не помню какой максимальный то ли около 30 толи около 50 мегабайт. Не могу точно ответить вопрос задавал более года назад . переписку не могу поднять.

Подписывать файл по частям .... как вариант, делить аргумент функции "base64". Но я в обще в принципе не иследовал вариант подписания файла частями и не знаю на сколько это возможно, и как потом проверить подпись и сам файл. Ведь это самое главное.

Если вдруг будет инфа какая либо, буду рад пул реквесту.
